#!/usr/bin/python3

import dbus
import os
import subprocess

try:
	# Get the firefox instance name
	script_location = os.environ["DOTFILES_SCRIPTS"] + "/music-control.sh"
	result = subprocess.run([script_location, 'getinfo'], stdout=subprocess.PIPE)
	instance_name = result.stdout.decode("utf-8").strip()

	bus = dbus.SessionBus()
	firefox = bus.get_object("org.mpris.MediaPlayer2." + instance_name, "/org/mpris/MediaPlayer2")
	firefox_iface = dbus.Interface(firefox, 'org.freedesktop.DBus.Properties')
	props = firefox_iface.Get('org.mpris.MediaPlayer2.Player', 'Metadata')

	output = "<span background='#005ab3' color='#ffffff'>" + "  ♫  " +  str(props['xesam:artist'][0]) + " - " + str(props['xesam:title']) + "  </span>"
	print(output.replace("&", "&amp;"))
	exit
except dbus.exceptions.DBusException:
	exit
except KeyError:
	exit



