#!/bin/bash

export BROWSER="/usr/bin/firefox"
export EDITOR="/usr/bin/nvim"
export DOTFILES="$HOME/dotfiles"
export DOTFILES_SCRIPTS="$DOTFILES/scripts"

[ -f "$DOTFILES/aliases/env-$(hostname)" ] && source "$DOTFILES/aliases/env-$(hostname)"
