#!/bin/bash

export PATH="$PATH:/opt/cisco/anyconnect/bin/:/opt/fah/:/usr/NX/bin/:$HOME/gems/bin:$HOME/.gem/ruby/2.7.0/bin:$HOME/.dotnet/tools:$HOME/.cargo/bin:$HOME/perl5:$HOME/.local/bin"

export TERMINAL="/usr/bin/alacritty"
export BROWSER="MOZ_USE_XINPUT2=1 MOZ_WEBRENDER=1 /usr/bin/firefox"
export EDITOR="/usr/bin/nvim"
export DOTFILES="$HOME/dotfiles"
export DOTFILES_SCRIPTS="$DOTFILES/scripts"

[ -f "$DOTFILES/aliases/env-$(hostname)" ] && source "$DOTFILES/aliases/env-$(hostname)"

export GEM_HOME="$HOME/gems"
export IPYTHONDIR="$DOTFILES/.config/ipython"

export QT_QPA_PLATFORMTHEME=qt5ct

GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export SDL_JOYSTICK_HIDAPI=0
